"""
mpp-pr — PR diff pattern checker. Outputs a GitHub-flavoured markdown comment.

Reads a unified diff from stdin or a file argument, runs find_by_trigger() on
the added code in each changed file, and prints a markdown report.

The GitHub Actions workflow pipes this output to `gh pr comment`.

Usage:
    git diff origin/main...HEAD | mpp-pr
    mpp-pr path/to/pr.diff
    python -m mpp.patterns.pr_check path/to/pr.diff
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class FileMatch:
    filename: str
    added_lines: list[str] = field(default_factory=list)
    pattern_ids: list[str] = field(default_factory=list)


def _parse_diff(diff: str) -> list[FileMatch]:
    """Split a unified diff into per-file buckets of added lines."""
    files: list[FileMatch] = []
    current: Optional[FileMatch] = None
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            current = FileMatch(filename=line[6:])
            files.append(current)
        elif current and line.startswith("+") and not line.startswith("+++"):
            current.added_lines.append(line[1:])
    return [f for f in files if f.added_lines]


def _run_checks(files: list[FileMatch], registry) -> list[FileMatch]:
    for fm in files:
        text = " ".join(fm.added_lines)
        if not text.strip():
            continue
        cards = registry.find_by_trigger(text)
        seen: set[str] = set()
        for c in cards:
            if c.id not in seen:
                seen.add(c.id)
                fm.pattern_ids.append(c.id)
    return [f for f in files if f.pattern_ids]


def _render_markdown(matches: list[FileMatch], registry) -> str:
    if not matches:
        return ""

    total = sum(len(f.pattern_ids) for f in matches)
    lines: list[str] = [
        "## MPP Pattern Check",
        "",
        f"> **{total} pattern signal(s)** detected across {len(matches)} file(s). "
        "Review before merging.",
        "",
    ]

    for fm in matches:
        lines.append(f"### `{fm.filename}`")
        lines.append("")
        for pid in fm.pattern_ids:
            try:
                card = registry.get(pid)
                lines.append(f"**{pid}** — {card.name}")
                diag = (card.diagnostic or "")[:200]
                if diag:
                    lines.append(f"> {diag}")
                if card.questions:
                    lines.append("")
                    lines.append("Diagnostic questions:")
                    for q in card.questions[:3]:
                        lines.append(f"- {q}")
            except Exception:
                lines.append(f"**{pid}**")
            lines.append("")

    lines += [
        "---",
        "<sub>Generated by [mpp-patterns](https://github.com/your-org/mpp-patterns). "
        "File a waiver in `gov/ADVERSARIAL_MMD.md` if this pattern does not apply.</sub>",
    ]
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) > 1:
        diff = Path(sys.argv[1]).read_text()
    elif not sys.stdin.isatty():
        diff = sys.stdin.read()
    else:
        print("Usage: git diff origin/main...HEAD | mpp-pr", file=sys.stderr)
        sys.exit(1)

    try:
        sys.path.insert(0, str(Path(__file__).parent.parent.parent))
        from mpp.patterns.pattern_registry import PatternRegistry
        registry = PatternRegistry()
    except Exception as exc:
        print(f"[mpp-pr] registry unavailable: {exc}", file=sys.stderr)
        sys.exit(0)

    files = _parse_diff(diff)
    matches = _run_checks(files, registry)
    report = _render_markdown(matches, registry)
    if report:
        print(report)


if __name__ == "__main__":
    main()
